import { useCallback, useEffect, useRef, useState, type KeyboardEvent } from 'react';
import { toast } from 'sonner';

import { site } from '@/content/site';
import { useScrollToSection } from '@/hooks/use-section-nav';
import {
  clearsScreen,
  complete,
  runCommand,
  type CommandContext,
  type Line,
} from '@/lib/terminal-commands';
import { promptPath } from '@/lib/terminal-fs';
import { cn } from '@/lib/utils';

/**
 * A working shell in the hero.
 *
 * This replaced `AsciiSculpture` — a genuine software 3D renderer that printed
 * a rotating torus to characters. It was well built and Sahil still cut it, and
 * the reason is worth keeping: it was *impressive*, but it wasn't *evidence*. A
 * visitor who lands here can now type `ls`, `projects`, `open work` and reach
 * the actual content in three keystrokes, which is a stronger opening claim
 * than a spinning solid.
 *
 * Everything runs on the same engine as the full terminal on /lab —
 * `runCommand` over a filesystem generated from the content modules. There is
 * no second command table to drift out of sync; this component is a smaller
 * window onto the same shell.
 *
 * **The height is fixed and the buffer scrolls inside it.** The hero is the
 * first thing anyone sees and it must not resize as output accumulates: `cat`
 * on a project file prints twenty lines, and a hero that grows by twenty lines
 * shoves the rest of the page down while the visitor is reading it.
 */

const lineClass: Record<Line['kind'], string> = {
  in: 'text-foreground',
  out: 'text-muted-foreground',
  err: 'text-destructive',
  accent: 'text-primary',
};

/** The command the shell runs for you before you touch it. */
const BOOT_COMMAND = 'neofetch';

/**
 * The opening buffer: the echoed prompt, then `neofetch`'s *real* output.
 *
 * Generated by `runCommand`, never transcribed. A hardcoded copy would be a
 * screenshot of a command rather than the command — the exact thing this
 * terminal exists to avoid — and it would silently go stale the moment a
 * project is added, since neofetch counts them from the content modules.
 *
 * The context is a stub: `neofetch` touches none of it, and wiring the live one
 * in would mean building the callbacks before the component exists.
 */
const bootBuffer = (): Line[] => [
  { kind: 'in', text: `${promptPath([])} $ ${BOOT_COMMAND}` },
  ...runCommand(BOOT_COMMAND, {
    cwd: [],
    setCwd: () => {},
    clear: () => {},
    scrollTo: () => {},
    copyEmail: () => {},
    history: [],
    toggleFullscreen: () => {},
  }),
  { kind: 'out', text: "Type 'help' for commands, or 'ls' to look around." },
  { kind: 'out', text: '' },
];

const HINTS: Array<[string, string]> = [
  ['help', 'commands'],
  ['ls', 'list'],
  ['projects', 'work'],
  ['neofetch', 'summary'],
  ['cls', 'clear'],
];

/**
 * Read synchronously rather than through framer's `useReducedMotion`, which
 * returns null on the first render and only resolves after an effect. That's
 * fine for an animation, but here it decides the *initial* buffer — and a hook
 * that says "not yet" on mount would leave a reduced-motion visitor staring at
 * an empty screen with no timers left to fill it.
 */
const prefersReducedMotion = () =>
  typeof window !== 'undefined' && window.matchMedia('(prefers-reduced-motion: reduce)').matches;

export const HeroTerminal = ({ className }: { className?: string }) => {
  const [lines, setLines] = useState<Line[]>(() => (prefersReducedMotion() ? bootBuffer() : []));
  /**
   * Whether the prompt is accepting input — tracked separately from the buffer.
   *
   * It used to be inferred as `lines.length >= GREETING.length`, which is true
   * right up until someone types `clear` or `cls`: the buffer empties, the
   * condition goes false, and the input vanishes. You are left looking at a
   * terminal you cannot type into and whose only recovery is a page reload.
   * "Has the greeting finished" and "is the screen empty" are two different
   * questions and must not share one answer.
   */
  const [ready, setReady] = useState(() => prefersReducedMotion());
  const [cwd, setCwd] = useState<string[]>([]);
  const [input, setInput] = useState('');
  const [history, setHistory] = useState<string[]>([]);
  const [historyIndex, setHistoryIndex] = useState(-1);

  const inputRef = useRef<HTMLInputElement>(null);
  const scrollRef = useRef<HTMLDivElement>(null);

  /* Types itself in a line at a time — the hero should look alive on arrival.
     Note what it is *not*: a fake boot log with invented "[ OK ] mounting"
     steps. It is a real command, really executed, printing real counts from the
     content modules. Under reduced motion it is all present on the first frame. */
  useEffect(() => {
    if (prefersReducedMotion()) return;
    const buffer = bootBuffer();
    // Typed in a line at a time so the hero is alive on arrival. Faster than
    // the /lab boot log because there is more of it and nobody should wait
    // three seconds to reach a prompt on the first screen.
    const timers = buffer.map((line, i) =>
      setTimeout(() => setLines((prev) => [...prev, line]), 500 + i * 55),
    );
    timers.push(setTimeout(() => setReady(true), 500 + buffer.length * 55));
    return () => timers.forEach(clearTimeout);
  }, []);

  // Newest output stays in view — inside this pane, never by moving the page.
  useEffect(() => {
    const el = scrollRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [lines]);

  const copyEmail = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(site.email);
      toast.success('Email copied to clipboard');
    } catch {
      window.location.href = `mailto:${site.email}`;
    }
  }, []);

  const scrollToSection = useScrollToSection();

  const submit = useCallback(
    (raw: string) => {
      const prompt = `${promptPath(cwd)} $ ${raw}`;
      const ctx: CommandContext = {
        cwd,
        setCwd,
        clear: () => setLines([]),
        scrollTo: scrollToSection,
        copyEmail,
        history,
        // No fullscreen from the hero — the full window lives on /lab, and a
        // hero control that takes over the viewport on the first screen is a
        // trap, not a feature.
        toggleFullscreen: () => scrollToSection('lab-teaser'),
      };

      const result = runCommand(raw, ctx);

      setLines((prev) =>
        clearsScreen(raw) ? [] : [...prev, { kind: 'in', text: prompt }, ...result],
      );

      if (raw.trim()) setHistory((h) => [raw, ...h].slice(0, 60));
      setHistoryIndex(-1);
      setInput('');
    },
    [cwd, scrollToSection, copyEmail, history],
  );

  const onKeyDown = (e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      e.preventDefault();
      submit(input);
      return;
    }

    if (e.key === 'Tab') {
      e.preventDefault();
      const completed = complete(input, cwd);
      if (completed) setInput(completed);
      return;
    }

    if (e.key === 'l' && e.ctrlKey) {
      e.preventDefault();
      setLines([]);
      return;
    }

    if (e.key === 'ArrowUp') {
      e.preventDefault();
      const next = Math.min(historyIndex + 1, history.length - 1);
      if (next >= 0 && history[next] !== undefined) {
        setHistoryIndex(next);
        setInput(history[next]);
      }
      return;
    }

    if (e.key === 'ArrowDown') {
      e.preventDefault();
      const next = historyIndex - 1;
      if (next < 0) {
        setHistoryIndex(-1);
        setInput('');
      } else {
        setHistoryIndex(next);
        setInput(history[next] ?? '');
      }
    }
  };

  return (
    <div
      onClick={() => inputRef.current?.focus()}
      className={cn('glass flex flex-col overflow-hidden rounded-2xl shadow-2xl', className)}
    >
      {/* Chrome */}
      <div className="flex shrink-0 items-center gap-2 border-b border-white/[0.06] bg-elevated/60 px-4 py-2.5">
        <span className="h-2.5 w-2.5 rounded-full bg-[#FF5F57]/70" />
        <span className="h-2.5 w-2.5 rounded-full bg-[#FEBC2E]/70" />
        <span className="h-2.5 w-2.5 rounded-full bg-[#28C840]/70" />
        <span className="ml-2 min-w-0 flex-1 truncate font-mono text-[0.62rem] tracking-wide text-muted-foreground">
          {site.shortName.toLowerCase()}@portfolio — {promptPath(cwd)}
        </span>
      </div>

      {/* Screen. Fixed height + its own scrollbar: the hero's height is a
          constant, whatever anyone types into it. Lenis is configured with
          allowNestedScroll, so reaching the end of the buffer hands the scroll
          back to the page instead of trapping it.

          Scrolls on BOTH axes, because the lines are `whitespace-pre`. Almost
          everything this shell prints is column-aligned — neofetch's art beside
          its info block, `ls`, `tree`, `help` — and soft-wrapping shears those
          columns apart on a narrow screen. Every real terminal scrolls
          horizontally instead, and the overflow stays inside this pane rather
          than on the page. */}
      <div
        ref={scrollRef}
        className="h-[20rem] overflow-auto overscroll-contain bg-background/60 p-4 font-mono text-[0.66rem] leading-[1.6] sm:h-[23rem] sm:text-[0.74rem]"
      >
        {lines.map((line, i) => (
          <pre
            key={i}
            className={cn('whitespace-pre font-mono', lineClass[line.kind])}
          >
            {line.text || ' '}
          </pre>
        ))}

        {ready && (
          <div className="mt-1 flex items-baseline gap-2">
            <span className="shrink-0 text-primary">{promptPath(cwd)}</span>
            <span className="shrink-0 text-muted-foreground">$</span>
            <input
              ref={inputRef}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={onKeyDown}
              spellCheck={false}
              autoComplete="off"
              autoCapitalize="off"
              autoCorrect="off"
              aria-label="Terminal input"
              className="min-w-0 flex-1 border-none bg-transparent font-mono text-foreground caret-primary outline-none placeholder:text-muted-foreground/40"
              placeholder="type 'help'…"
            />
          </div>
        )}
      </div>

      {/* Hint bar */}
      <div className="flex shrink-0 flex-wrap items-center gap-x-3 gap-y-1.5 border-t border-white/[0.06] bg-elevated/40 px-4 py-2.5">
        {HINTS.map(([cmd, label]) => (
          <button
            key={cmd}
            onClick={(e) => {
              e.stopPropagation();
              submit(cmd);
              inputRef.current?.focus();
            }}
            className="group flex min-h-9 items-center gap-1.5 font-mono text-[0.58rem] text-muted-foreground transition-colors hover:text-primary"
          >
            <span className="rounded border border-border bg-elevated px-1.5 py-0.5 transition-colors group-hover:border-primary/40">
              {cmd}
            </span>
            <span className="hidden xs:inline">{label}</span>
          </button>
        ))}
      </div>
    </div>
  );
};
